### ISSUE TITLE
Styling of widget

### ISSUE THREAD

**Issue by wrabit** [Moventes/bruit.io#24]
Assuming that the style in the screenshot does not reflect the intended style of the widget, the style rules should be more targeted to the widget's elements so any local stylesheet doesn't interfere.

Or make it easy to have user-defined styles.

Unless I am missing something in the docs about styling?

![image](https://user-images.githubusercontent.com/5918271/52856314-62578f80-3124-11e9-8cde-8b99797bacc8.png)

**Comment by ghost** [comment]
Hi,
To generate our screenshots, we use the library [html2canvas](https://html2canvas.hertzen.com/) which interprets the DOM of your website and renders it on a canvas from which an image is generated.
One downside of this method is that the tool uses its own logic to define the appearance of what is actually displayed on your browser, meaning there _might_ be differences between the web page and the rendered screenshot.
We keep up to date with this library so that any improvement on that side is reflected to bruit.io.

On a side note, using this library allows you to choose whether an element of your page will be rendered on the screenshot, namely you may tell html2canvas to ignore the bruit.io popup form by simply adding a data-html2canvas-ignore attribute on some parent element in the DOM.
You may refer to this [stackoverflow post](https://stackoverflow.com/a/27735422/1843141) for more information.

**Comment by wrabit** [comment]
@Malrok I think we have crossed wires, the screenshot I included is the rendered widget on my app. I'm not referring to the screenshot provided as part of the bug report.

**Comment by ghost** [comment]
@williamabbott my bad, I had misunderstood your problem.
Can you please tell me what OS / browser type and versions you are using?

**Comment by wrabit** [comment]
No probs,

Latest Macos
Latest Stable Chrome

**Comment by ghost** [comment]
@williamabbott  hi, this is fixed with version 1.0.4.
